export const GenresOption = {
  action: "Action",
  comedy: "Comedy",
  family: "Family",
  history: "History",
  mystery: "Mystery",
  sci_fi: "Sci-Fi",
  war: "War",
  adventure: "Adventure",
  crime: "Crime",
  fantasy: "Fantasy",
  horror: "Horror",
  news: "News",
  sport: "Sport",
  western: "Western",
  animation: "Animation",
  documentary: "Documentary",
  film_noir: "Film-Noir",
  music: "Music",
  reality_tv: "Reality-TV",
  talk_show: "Talk-Show",
  biography: "Biography",
  drama: "Drama",
  game_show: "Game-Show",
  musical: "Musical",
  romance: "Romance",
  thriller: "Thriller"
}
